//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperShopDesktop.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class En {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal En() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperShopDesktop.Language.En", typeof(En).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Manager.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Login_MainLogin_gbtn_exit {
            get {
                return ResourceManager.GetString("Login_MainLogin_gbtn_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Login_MainLogin_gbtn_setting {
            get {
                return ResourceManager.GetString("Login_MainLogin_gbtn_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Login_MainLogin_gbtn_signin {
            get {
                return ResourceManager.GetString("Login_MainLogin_gbtn_signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Login_MainLogin_gbtn_signup {
            get {
                return ResourceManager.GetString("Login_MainLogin_gbtn_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Login_Settings_gbtn_save {
            get {
                return ResourceManager.GetString("Login_Settings_gbtn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Login_Settings_gchb_show {
            get {
                return ResourceManager.GetString("Login_Settings_gchb_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        internal static string Login_Settings_glbl_database {
            get {
                return ResourceManager.GetString("Login_Settings_glbl_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_Settings_glbl_pass {
            get {
                return ResourceManager.GetString("Login_Settings_glbl_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Login_Settings_glbl_user {
            get {
                return ResourceManager.GetString("Login_Settings_glbl_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Login_Signin_gbtn_signin {
            get {
                return ResourceManager.GetString("Login_Signin_gbtn_signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Login_Signin_gchb_showpass {
            get {
                return ResourceManager.GetString("Login_Signin_gchb_showpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Login_Signin_glbl_email {
            get {
                return ResourceManager.GetString("Login_Signin_glbl_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password?.
        /// </summary>
        internal static string Login_Signin_glbl_forgotPassword {
            get {
                return ResourceManager.GetString("Login_Signin_glbl_forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_Signin_glbl_password {
            get {
                return ResourceManager.GetString("Login_Signin_glbl_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin account is blocked!.
        /// </summary>
        internal static string Login_SigninAdmin_adminBlocked {
            get {
                return ResourceManager.GetString("Login_SigninAdmin_adminBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin doesn&apos;t exist with this email!.
        /// </summary>
        internal static string Login_SigninAdmin_adminNotExist {
            get {
                return ResourceManager.GetString("Login_SigninAdmin_adminNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string Login_SigninAdmin_gbtn_signin {
            get {
                return ResourceManager.GetString("Login_SigninAdmin_gbtn_signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Login_SigninAdmin_gchb_showpass {
            get {
                return ResourceManager.GetString("Login_SigninAdmin_gchb_showpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Login_SigninAdmin_glbl_email {
            get {
                return ResourceManager.GetString("Login_SigninAdmin_glbl_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string Login_SigninAdmin_glbl_forgotPassword {
            get {
                return ResourceManager.GetString("Login_SigninAdmin_glbl_forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_SigninAdmin_glbl_password {
            get {
                return ResourceManager.GetString("Login_SigninAdmin_glbl_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is wrong!.
        /// </summary>
        internal static string Login_SigninAdmin_passwordWrong {
            get {
                return ResourceManager.GetString("Login_SigninAdmin_passwordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator doesn&apos;t exist with this email!.
        /// </summary>
        internal static string Login_SigninOperator_operatorNotExist {
            get {
                return ResourceManager.GetString("Login_SigninOperator_operatorNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is wrong!.
        /// </summary>
        internal static string Login_SigninOperator_passwordWrong {
            get {
                return ResourceManager.GetString("Login_SigninOperator_passwordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string Login_Signup_gbtn_signup {
            get {
                return ResourceManager.GetString("Login_Signup_gbtn_signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sow.
        /// </summary>
        internal static string Login_Signup_gchb_showpass {
            get {
                return ResourceManager.GetString("Login_Signup_gchb_showpass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string Login_Signup_glbl_confirmPassword {
            get {
                return ResourceManager.GetString("Login_Signup_glbl_confirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Login_Signup_glbl_email {
            get {
                return ResourceManager.GetString("Login_Signup_glbl_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Login_Signup_glbl_name {
            get {
                return ResourceManager.GetString("Login_Signup_glbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Login_Signup_glbl_password {
            get {
                return ResourceManager.GetString("Login_Signup_glbl_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Login_Signup_glbl_phone {
            get {
                return ResourceManager.GetString("Login_Signup_glbl_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Login_Signup_glbl_surname {
            get {
                return ResourceManager.GetString("Login_Signup_glbl_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password doesn&apos;t match!.
        /// </summary>
        internal static string Login_Signup_passwordNotMatch {
            get {
                return ResourceManager.GetString("Login_Signup_passwordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created!.
        /// </summary>
        internal static string Login_Signup_success {
            get {
                return ResourceManager.GetString("Login_Signup_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid email.
        /// </summary>
        internal static string Login_Signup_validEmail {
            get {
                return ResourceManager.GetString("Login_Signup_validEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin already exists with this email!.
        /// </summary>
        internal static string Login_SignupAdmin_adminExistEmail {
            get {
                return ResourceManager.GetString("Login_SignupAdmin_adminExistEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin already exists with this phone!.
        /// </summary>
        internal static string Login_SignupAdmin_adminExistPhone {
            get {
                return ResourceManager.GetString("Login_SignupAdmin_adminExistPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill information fully!.
        /// </summary>
        internal static string Login_SignupAdmin_fullInformation {
            get {
                return ResourceManager.GetString("Login_SignupAdmin_fullInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill information fully!.
        /// </summary>
        internal static string Login_SignupOper_fullInformation {
            get {
                return ResourceManager.GetString("Login_SignupOper_fullInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator already exists with this email!.
        /// </summary>
        internal static string Login_SignupOper_operExistEmail {
            get {
                return ResourceManager.GetString("Login_SignupOper_operExistEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator already exists with this phone!.
        /// </summary>
        internal static string Login_SignupOper_operExistPhone {
            get {
                return ResourceManager.GetString("Login_SignupOper_operExistPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier.
        /// </summary>
        internal static string Main_AddNew_gbtn_cashier {
            get {
                return ResourceManager.GetString("Main_AddNew_gbtn_cashier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product company.
        /// </summary>
        internal static string Main_AddNew_gbtn_company {
            get {
                return ResourceManager.GetString("Main_AddNew_gbtn_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product kind.
        /// </summary>
        internal static string Main_AddNew_gbtn_kind {
            get {
                return ResourceManager.GetString("Main_AddNew_gbtn_kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Main_AddNew_gbtn_product {
            get {
                return ResourceManager.GetString("Main_AddNew_gbtn_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbered Product.
        /// </summary>
        internal static string Main_AddNew_gbtn_productNumber {
            get {
                return ResourceManager.GetString("Main_AddNew_gbtn_productNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight product.
        /// </summary>
        internal static string Main_AddNew_gbtn_productWeight {
            get {
                return ResourceManager.GetString("Main_AddNew_gbtn_productWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        internal static string Main_AddNew_gbtn_worker {
            get {
                return ResourceManager.GetString("Main_AddNew_gbtn_worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker sector.
        /// </summary>
        internal static string Main_AddNew_gbtn_workSector {
            get {
                return ResourceManager.GetString("Main_AddNew_gbtn_workSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashiers.
        /// </summary>
        internal static string Main_MainAdmin_gbtn_cashiers {
            get {
                return ResourceManager.GetString("Main_MainAdmin_gbtn_cashiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Main_MainAdmin_gbtn_products {
            get {
                return ResourceManager.GetString("Main_MainAdmin_gbtn_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Main_MainAdmin_gbtn_settings {
            get {
                return ResourceManager.GetString("Main_MainAdmin_gbtn_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers.
        /// </summary>
        internal static string Main_MainAdmin_gbtn_workers {
            get {
                return ResourceManager.GetString("Main_MainAdmin_gbtn_workers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Main_Menu_CashierEdit_gbtn_remove {
            get {
                return ResourceManager.GetString("Main_Menu_CashierEdit_gbtn_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Main_Menu_CashierEdit_gbtn_reset {
            get {
                return ResourceManager.GetString("Main_Menu_CashierEdit_gbtn_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Main_Menu_CashierEdit_gbtn_save {
            get {
                return ResourceManager.GetString("Main_Menu_CashierEdit_gbtn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Main_Menu_CashierEdit_lbl_name {
            get {
                return ResourceManager.GetString("Main_Menu_CashierEdit_lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        internal static string Main_Menu_CashierEdit_lbl_worker {
            get {
                return ResourceManager.GetString("Main_Menu_CashierEdit_lbl_worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products left!.
        /// </summary>
        internal static string Main_Notification_lessProductNumberLeft {
            get {
                return ResourceManager.GetString("Main_Notification_lessProductNumberLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg left!.
        /// </summary>
        internal static string Main_Notification_lessProductWeightLeft {
            get {
                return ResourceManager.GetString("Main_Notification_lessProductWeightLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Main_ProductCompanyEdit_gbtn_save {
            get {
                return ResourceManager.GetString("Main_ProductCompanyEdit_gbtn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin date.
        /// </summary>
        internal static string Main_ProductCompanyEdit_lbl_beginDate {
            get {
                return ResourceManager.GetString("Main_ProductCompanyEdit_lbl_beginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Main_ProductCompanyEdit_lbl_email {
            get {
                return ResourceManager.GetString("Main_ProductCompanyEdit_lbl_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string Main_ProductCompanyEdit_lbl_endDate {
            get {
                return ResourceManager.GetString("Main_ProductCompanyEdit_lbl_endDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last come date.
        /// </summary>
        internal static string Main_ProductCompanyEdit_lbl_lastComeDate {
            get {
                return ResourceManager.GetString("Main_ProductCompanyEdit_lbl_lastComeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Main_ProductCompanyEdit_lbl_name {
            get {
                return ResourceManager.GetString("Main_ProductCompanyEdit_lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Main_ProductCompanyEdit_lbl_phone {
            get {
                return ResourceManager.GetString("Main_ProductCompanyEdit_lbl_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Main_ProductKindEdit_gbtn_save {
            get {
                return ResourceManager.GetString("Main_ProductKindEdit_gbtn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Main_ProductKindEdit_lbl_name {
            get {
                return ResourceManager.GetString("Main_ProductKindEdit_lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Main_ProductNumberEdit_gbtn_save {
            get {
                return ResourceManager.GetString("Main_ProductNumberEdit_gbtn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival price.
        /// </summary>
        internal static string Main_ProductNumberEdit_lbl_arrivalPrice {
            get {
                return ResourceManager.GetString("Main_ProductNumberEdit_lbl_arrivalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last come date.
        /// </summary>
        internal static string Main_ProductNumberEdit_lbl_lastComeDate {
            get {
                return ResourceManager.GetString("Main_ProductNumberEdit_lbl_lastComeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Main_ProductNumberEdit_lbl_name {
            get {
                return ResourceManager.GetString("Main_ProductNumberEdit_lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Main_ProductNumberEdit_lbl_number {
            get {
                return ResourceManager.GetString("Main_ProductNumberEdit_lbl_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        internal static string Main_ProductNumberEdit_lbl_productKind {
            get {
                return ResourceManager.GetString("Main_ProductNumberEdit_lbl_productKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale price.
        /// </summary>
        internal static string Main_ProductNumberEdit_lbl_salePrice {
            get {
                return ResourceManager.GetString("Main_ProductNumberEdit_lbl_salePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Main_Products_gcb_all {
            get {
                return ResourceManager.GetString("Main_Products_gcb_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Main_Products_gcb_company {
            get {
                return ResourceManager.GetString("Main_Products_gcb_company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        internal static string Main_Products_gcb_kind {
            get {
                return ResourceManager.GetString("Main_Products_gcb_kind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbered Products.
        /// </summary>
        internal static string Main_Products_gcb_productNumber {
            get {
                return ResourceManager.GetString("Main_Products_gcb_productNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Products.
        /// </summary>
        internal static string Main_Products_gcb_productWeight {
            get {
                return ResourceManager.GetString("Main_Products_gcb_productWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Main_ProductWeightEdit_gbtn_save {
            get {
                return ResourceManager.GetString("Main_ProductWeightEdit_gbtn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival price.
        /// </summary>
        internal static string Main_ProductWeightEdit_lbl_arrivalPrice {
            get {
                return ResourceManager.GetString("Main_ProductWeightEdit_lbl_arrivalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last come date.
        /// </summary>
        internal static string Main_ProductWeightEdit_lbl_lastComeDate {
            get {
                return ResourceManager.GetString("Main_ProductWeightEdit_lbl_lastComeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Main_ProductWeightEdit_lbl_name {
            get {
                return ResourceManager.GetString("Main_ProductWeightEdit_lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Main_ProductWeightEdit_lbl_productCompany {
            get {
                return ResourceManager.GetString("Main_ProductWeightEdit_lbl_productCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind.
        /// </summary>
        internal static string Main_ProductWeightEdit_lbl_productKind {
            get {
                return ResourceManager.GetString("Main_ProductWeightEdit_lbl_productKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale price.
        /// </summary>
        internal static string Main_ProductWeightEdit_lbl_salePrice {
            get {
                return ResourceManager.GetString("Main_ProductWeightEdit_lbl_salePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Main_ProductWeightEdit_lbl_weight {
            get {
                return ResourceManager.GetString("Main_ProductWeightEdit_lbl_weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Main_Remove {
            get {
                return ResourceManager.GetString("Main_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijan.
        /// </summary>
        internal static string Main_Settings_cb_azerbaijan {
            get {
                return ResourceManager.GetString("Main_Settings_cb_azerbaijan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Main_Settings_cb_english {
            get {
                return ResourceManager.GetString("Main_Settings_cb_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Main_Settings_lbl_language {
            get {
                return ResourceManager.GetString("Main_Settings_lbl_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove?.
        /// </summary>
        internal static string Main_SureRemove {
            get {
                return ResourceManager.GetString("Main_SureRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Main_WorkerEdit_lbl_address {
            get {
                return ResourceManager.GetString("Main_WorkerEdit_lbl_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Main_WorkerEdit_lbl_birthday {
            get {
                return ResourceManager.GetString("Main_WorkerEdit_lbl_birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Main_WorkerEdit_lbl_birthdayHeader {
            get {
                return ResourceManager.GetString("Main_WorkerEdit_lbl_birthdayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Main_WorkerEdit_lbl_contact {
            get {
                return ResourceManager.GetString("Main_WorkerEdit_lbl_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Main_WorkerEdit_lbl_email {
            get {
                return ResourceManager.GetString("Main_WorkerEdit_lbl_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        internal static string Main_workerEdit_lbl_endTime {
            get {
                return ResourceManager.GetString("Main_workerEdit_lbl_endTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father name.
        /// </summary>
        internal static string Main_WorkerEdit_lbl_fatherName {
            get {
                return ResourceManager.GetString("Main_WorkerEdit_lbl_fatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Main_WorkerEdit_lbl_name {
            get {
                return ResourceManager.GetString("Main_WorkerEdit_lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Main_WorkerEdit_lbl_phone {
            get {
                return ResourceManager.GetString("Main_WorkerEdit_lbl_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        internal static string Main_WorkerEdit_lbl_sector {
            get {
                return ResourceManager.GetString("Main_WorkerEdit_lbl_sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        internal static string Main_WorkerEdit_lbl_sectorHeader {
            get {
                return ResourceManager.GetString("Main_WorkerEdit_lbl_sectorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string Main_workerEdit_lbl_startTime {
            get {
                return ResourceManager.GetString("Main_workerEdit_lbl_startTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string Main_WorkerEdit_lbl_surname {
            get {
                return ResourceManager.GetString("Main_WorkerEdit_lbl_surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage.
        /// </summary>
        internal static string Main_WorkerEdit_lbl_wage {
            get {
                return ResourceManager.GetString("Main_WorkerEdit_lbl_wage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage.
        /// </summary>
        internal static string Main_WorkerEdit_lbl_wageHeader {
            get {
                return ResourceManager.GetString("Main_WorkerEdit_lbl_wageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Time.
        /// </summary>
        internal static string Main_WorkerEdit_lbl_workTimeHeader {
            get {
                return ResourceManager.GetString("Main_WorkerEdit_lbl_workTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Main_Workers_cb_all {
            get {
                return ResourceManager.GetString("Main_Workers_cb_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        internal static string Main_Workers_cb_sector {
            get {
                return ResourceManager.GetString("Main_Workers_cb_sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Main_WorkerView_lbl_address {
            get {
                return ResourceManager.GetString("Main_WorkerView_lbl_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Main_WorkerView_lbl_birthday {
            get {
                return ResourceManager.GetString("Main_WorkerView_lbl_birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Main_WorkerView_lbl_birthdayHeader {
            get {
                return ResourceManager.GetString("Main_WorkerView_lbl_birthdayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Main_WorkerView_lbl_contact {
            get {
                return ResourceManager.GetString("Main_WorkerView_lbl_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Main_WorkerView_lbl_email {
            get {
                return ResourceManager.GetString("Main_WorkerView_lbl_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string Main_WorkerView_lbl_endTime {
            get {
                return ResourceManager.GetString("Main_WorkerView_lbl_endTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Surname FatherName.
        /// </summary>
        internal static string Main_WorkerView_lbl_nameSurname {
            get {
                return ResourceManager.GetString("Main_WorkerView_lbl_nameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Main_WorkerView_lbl_phone {
            get {
                return ResourceManager.GetString("Main_WorkerView_lbl_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        internal static string Main_WorkerView_lbl_sector {
            get {
                return ResourceManager.GetString("Main_WorkerView_lbl_sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        internal static string Main_WorkerView_lbl_sectorHeader {
            get {
                return ResourceManager.GetString("Main_WorkerView_lbl_sectorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string Main_WorkerView_lbl_startTime {
            get {
                return ResourceManager.GetString("Main_WorkerView_lbl_startTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage.
        /// </summary>
        internal static string Main_WorkerView_lbl_wage {
            get {
                return ResourceManager.GetString("Main_WorkerView_lbl_wage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wage.
        /// </summary>
        internal static string Main_WorkerView_lbl_wageHeader {
            get {
                return ResourceManager.GetString("Main_WorkerView_lbl_wageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Time.
        /// </summary>
        internal static string Main_WorkerView_lbl_workTimeHeader {
            get {
                return ResourceManager.GetString("Main_WorkerView_lbl_workTimeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Main_WorkSector_gbtn_save {
            get {
                return ResourceManager.GetString("Main_WorkSector_gbtn_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Main_WorkSector_lbl_name {
            get {
                return ResourceManager.GetString("Main_WorkSector_lbl_name", resourceCulture);
            }
        }
    }
}
